name: liikelaaj
channels:
  - defaults
dependencies:
  - future
  - python
  - openpyxl
  - jupyter
  - pyqt
  - spyder
  - xlrd
  - xlsxwriter
  - xlutils
  - pip:
    - flake8
    - pytest
    - git+https://github.com/jjnurminen/ulstools.git#egg=ulstools

