name: liikelaaj
channels:
  - defaults
dependencies:
  - future
  - python=3.6
  - openpyxl
  - jupyter
  - pyqt
  - spyder
  - xlrd
  - xlsxwriter
  - xlutils
  - pip
  - pip:
    - flake8
    - pypdf2
    - pytest
    - https://github.com/jjnurminen/liikelaaj/archive/master.zip
    - https://github.com/jjnurminen/ulstools/archive/master.zip
